### ISSUE TITLE
Making a search causes panic

### ISSUE THREAD

**Issue by mradkov** [woxjro/lazy-etherscan#3]
Trying to make a search causes the program to panic. More precisely the unwrap here: https://github.com/woxjro/lazy-etherscan/blob/283c663914c2d9d390709d355e9afc4bf5608a3e/src/network.rs#L145

stack trace:
![image](https://github.com/woxjro/lazy-etherscan/assets/13139371/d9fe76ab-b29c-40fc-9953-16aee08df2bf)

### Steps to reproduce

1. search for `dai`

**Comment by woxjro** [comment]
@mradkov 
Thank you for submitting the detailed crash report!
I reproduced the bug. The search functionality is in the early stages, so be patient with it. I'm going to fix it as soon as possible.

**Comment by woxjro** [comment]
I suppose this commit has solved this issue. I'll close this issue.
5bdfa824d53a1de9508102986e24bfee6b3c1f0a
![Screenshot from 2023-11-04 02-26-17](https://github.com/woxjro/lazy-etherscan/assets/63214188/08daaffa-ec8d-44af-9a4c-9557429e7c00)
